// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ronfxeadqmrftgzxxpyw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJvbmZ4ZWFkcW1yZnRnenh4cHl3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2MDk1ODMsImV4cCI6MjA2NjE4NTU4M30.-Qf814_PrGqKzIejBL5lt6Quz8JBjujEzgmj7ExpvXI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);